### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by ZsiGiT** [leon-h-a/jellyfork#12]
Great plugin.

Please add "rename and copy" as a second option. Also, the subdirectory name within the movies directory should be the same as the file name. Example based on the demo video:

- /mnt/media/movies
   - The General (1926)
       - The General (1926).mp4

All my movies are in this structure, and it would make it much easier to manage them.

Many thanks

**Comment by leon-h-a** [comment]
Great to hear,
I'll add it this weekend.
Cheers

**Comment by leon-h-a** [comment]
I've added copy option via separate button and nesting via checkbox.
Let me know if you encounter any issues, enjoy 👍
